# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.control_tree_response_data_customers_customer_id_sites_site_id import ControlTreeResponseDataCustomersCustomerIdSitesSiteId  # noqa: E501
from swagger_client.rest import ApiException


class TestControlTreeResponseDataCustomersCustomerIdSitesSiteId(unittest.TestCase):
    """ControlTreeResponseDataCustomersCustomerIdSitesSiteId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testControlTreeResponseDataCustomersCustomerIdSitesSiteId(self):
        """Test ControlTreeResponseDataCustomersCustomerIdSitesSiteId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.control_tree_response_data_customers_customer_id_sites_site_id.ControlTreeResponseDataCustomersCustomerIdSitesSiteId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
