# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.zone_api import ZoneApi  # noqa: E501
from swagger_client.rest import ApiException


class TestZoneApi(unittest.TestCase):
    """ZoneApi unit test stubs"""

    def setUp(self):
        self.api = ZoneApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_zones_zone_id_delete(self):
        """Test case for zones_zone_id_delete

        delete zone  # noqa: E501
        """
        pass

    def test_zones_zone_id_get(self):
        """Test case for zones_zone_id_get

        get zone  # noqa: E501
        """
        pass

    def test_zones_zone_id_put(self):
        """Test case for zones_zone_id_put

        update zone  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
