# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.websocket_api import WebsocketApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWebsocketApi(unittest.TestCase):
    """WebsocketApi unit test stubs"""

    def setUp(self):
        self.api = WebsocketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_root_get(self):
        """Test case for root_get

        Websocket connection endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
