# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_control_api import SystemControlApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemControlApi(unittest.TestCase):
    """SystemControlApi unit test stubs"""

    def setUp(self):
        self.api = SystemControlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_systems_system_id_controls_modes_put(self):
        """Test case for systems_system_id_controls_modes_put

        set system active operation mode for all units  # noqa: E501
        """
        pass

    def test_systems_system_id_controls_switches_put(self):
        """Test case for systems_system_id_controls_switches_put

        set system active operation status for all units  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
