# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.zones_response import ZonesResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestZonesResponse(unittest.TestCase):
    """ZonesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZonesResponse(self):
        """Test ZonesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.zones_response.ZonesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
