# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.zone_control_fans_body import ZoneControlFansBody  # noqa: E501
from swagger_client.rest import ApiException


class TestZoneControlFansBody(unittest.TestCase):
    """ZoneControlFansBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZoneControlFansBody(self):
        """Test ZoneControlFansBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.zone_control_fans_body.ZoneControlFansBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
