# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bad_response401 import BadResponse401  # noqa: E501
from swagger_client.rest import ApiException


class TestBadResponse401(unittest.TestCase):
    """BadResponse401 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBadResponse401(self):
        """Test BadResponse401"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bad_response401.BadResponse401()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
