# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.site_api import SiteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSiteApi(unittest.TestCase):
    """SiteApi unit test stubs"""

    def setUp(self):
        self.api = SiteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sites_site_id_delete(self):
        """Test case for sites_site_id_delete

        delete site  # noqa: E501
        """
        pass

    def test_sites_site_id_get(self):
        """Test case for sites_site_id_get

        get site  # noqa: E501
        """
        pass

    def test_sites_site_id_put(self):
        """Test case for sites_site_id_put

        update site  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
