# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.zones_api import ZonesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestZonesApi(unittest.TestCase):
    """ZonesApi unit test stubs"""

    def setUp(self):
        self.api = ZonesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_zones_get(self):
        """Test case for zones_get

        get my zones  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
