# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_zone_request_body import CreateZoneRequestBody  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateZoneRequestBody(unittest.TestCase):
    """CreateZoneRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateZoneRequestBody(self):
        """Test CreateZoneRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_zone_request_body.CreateZoneRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
