# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.devices_response_data import DevicesResponseData  # noqa: E501
from swagger_client.rest import ApiException


class TestDevicesResponseData(unittest.TestCase):
    """DevicesResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDevicesResponseData(self):
        """Test DevicesResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.devices_response_data.DevicesResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
