# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unit_control_modes_body import UnitControlModesBody  # noqa: E501
from swagger_client.rest import ApiException


class TestUnitControlModesBody(unittest.TestCase):
    """UnitControlModesBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitControlModesBody(self):
        """Test UnitControlModesBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unit_control_modes_body.UnitControlModesBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
