# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_zone_request_body import UpdateZoneRequestBody  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateZoneRequestBody(unittest.TestCase):
    """UpdateZoneRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateZoneRequestBody(self):
        """Test UpdateZoneRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_zone_request_body.UpdateZoneRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
