# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.admins_api import AdminsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdminsApi(unittest.TestCase):
    """AdminsApi unit test stubs"""

    def setUp(self):
        self.api = AdminsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admins_customers_post(self):
        """Test case for admins_customers_post

        create customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
