# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.customers_response_data import CustomersResponseData

class TestCustomersResponseData(unittest.TestCase):
    """CustomersResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomersResponseData:
        """Test CustomersResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomersResponseData`
        """
        model = CustomersResponseData()
        if include_optional:
            return CustomersResponseData(
                customer_id = cool_open_client.client.models.customer_response_data.customerResponseData(
                    id = '', 
                    name = '', 
                    description = '', 
                    role = cool_open_client.client.models.role.role(), 
                    sites = [
                        ''
                        ], )
            )
        else:
            return CustomersResponseData(
        )
        """

    def testCustomersResponseData(self):
        """Test CustomersResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
