# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.api.customer_users_api import CustomerUsersApi  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestCustomerUsersApi(unittest.TestCase):
    """CustomerUsersApi unit test stubs"""

    def setUp(self):
        self.api = CustomerUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_customers_customer_id_users_get(self):
        """Test case for customers_customer_id_users_get

        get customer users  # noqa: E501
        """
        pass

    def test_customers_customer_id_users_post(self):
        """Test case for customers_customer_id_users_post

        create customer user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
