# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.update_unit_request_body import UpdateUnitRequestBody

class TestUpdateUnitRequestBody(unittest.TestCase):
    """UpdateUnitRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUnitRequestBody:
        """Test UpdateUnitRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUnitRequestBody`
        """
        model = UpdateUnitRequestBody()
        if include_optional:
            return UpdateUnitRequestBody(
                name = '',
                type = 56,
                supported_switch_modes = [
                    56
                    ],
                supported_modes = [
                    56
                    ],
                supported_fan_modes = [
                    56
                    ],
                supported_swing_modes = [
                    56
                    ],
                temperature_limits = None
            )
        else:
            return UpdateUnitRequestBody(
        )
        """

    def testUpdateUnitRequestBody(self):
        """Test UpdateUnitRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
