# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: none@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.models.types_response_data_week_days import TypesResponseDataWeekDays  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestTypesResponseDataWeekDays(unittest.TestCase):
    """TypesResponseDataWeekDays unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypesResponseDataWeekDays(self):
        """Test TypesResponseDataWeekDays"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cool_open_client.client.models.types_response_data_week_days.TypesResponseDataWeekDays()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
