# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.device_units_api import DeviceUnitsApi


class TestDeviceUnitsApi(unittest.IsolatedAsyncioTestCase):
    """DeviceUnitsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DeviceUnitsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_devices_device_id_units_get(self) -> None:
        """Test case for devices_device_id_units_get

        get device units
        """
        pass


if __name__ == '__main__':
    unittest.main()
