# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: none@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.api.me_api import MeApi  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestMeApi(unittest.TestCase):
    """MeApi unit test stubs"""

    def setUp(self):
        self.api = MeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_me_get(self):
        """Test case for users_me_get

        get me  # noqa: E501
        """
        pass

    def test_users_me_tree_get(self):
        """Test case for users_me_tree_get

        get my control tree  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
