# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.models.control_tree_response_data_customers_customer_id_sites import ControlTreeResponseDataCustomersCustomerIdSites  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestControlTreeResponseDataCustomersCustomerIdSites(unittest.TestCase):
    """ControlTreeResponseDataCustomersCustomerIdSites unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testControlTreeResponseDataCustomersCustomerIdSites(self):
        """Test ControlTreeResponseDataCustomersCustomerIdSites"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cool_open_client.client.models.control_tree_response_data_customers_customer_id_sites.ControlTreeResponseDataCustomersCustomerIdSites()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
