# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.create_user_request_body import CreateUserRequestBody

class TestCreateUserRequestBody(unittest.TestCase):
    """CreateUserRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUserRequestBody:
        """Test CreateUserRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUserRequestBody`
        """
        model = CreateUserRequestBody()
        if include_optional:
            return CreateUserRequestBody(
                username = '',
                password = '',
                temperature_scale = 56,
                permissions = None,
                first_name = '',
                last_name = '',
                email = '',
                phone = ''
            )
        else:
            return CreateUserRequestBody(
                username = '',
                password = '',
                temperature_scale = 56,
                permissions = None,
        )
        """

    def testCreateUserRequestBody(self):
        """Test CreateUserRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
