# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.users_api import UsersApi


class TestUsersApi(unittest.IsolatedAsyncioTestCase):
    """UsersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UsersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_users_get(self) -> None:
        """Test case for users_get

        get my users
        """
        pass


if __name__ == '__main__':
    unittest.main()
