# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.models.update_customer_request_body import UpdateCustomerRequestBody  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestUpdateCustomerRequestBody(unittest.TestCase):
    """UpdateCustomerRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateCustomerRequestBody(self):
        """Test UpdateCustomerRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cool_open_client.client.models.update_customer_request_body.UpdateCustomerRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
