# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.api.zone_control_api import ZoneControlApi  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestZoneControlApi(unittest.TestCase):
    """ZoneControlApi unit test stubs"""

    def setUp(self):
        self.api = ZoneControlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_zones_zone_id_controls_fans_put(self):
        """Test case for zones_zone_id_controls_fans_put

        set zone active fan mode for all units  # noqa: E501
        """
        pass

    def test_zones_zone_id_controls_modes_put(self):
        """Test case for zones_zone_id_controls_modes_put

        set zone active operation mode for all units  # noqa: E501
        """
        pass

    def test_zones_zone_id_controls_setpoints_put(self):
        """Test case for zones_zone_id_controls_setpoints_put

        set zone active temperature setpoint for all units  # noqa: E501
        """
        pass

    def test_zones_zone_id_controls_switches_put(self):
        """Test case for zones_zone_id_controls_switches_put

        set zone active operation status for all units  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
