# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.me_api import MeApi


class TestMeApi(unittest.IsolatedAsyncioTestCase):
    """MeApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MeApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_users_me_get(self) -> None:
        """Test case for users_me_get

        get me
        """
        pass

    async def test_users_me_tree_get(self) -> None:
        """Test case for users_me_tree_get

        get my control tree
        """
        pass


if __name__ == '__main__':
    unittest.main()
