# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.system_api import SystemApi


class TestSystemApi(unittest.IsolatedAsyncioTestCase):
    """SystemApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SystemApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_systems_system_id_delete(self) -> None:
        """Test case for systems_system_id_delete

        delete system
        """
        pass

    async def test_systems_system_id_get(self) -> None:
        """Test case for systems_system_id_get

        get system
        """
        pass

    async def test_systems_system_id_put(self) -> None:
        """Test case for systems_system_id_put

        update system
        """
        pass


if __name__ == '__main__':
    unittest.main()
