# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.customer_api import CustomerApi


class TestCustomerApi(unittest.IsolatedAsyncioTestCase):
    """CustomerApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CustomerApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_customers_customer_id_delete(self) -> None:
        """Test case for customers_customer_id_delete

        delete customer
        """
        pass

    async def test_customers_customer_id_get(self) -> None:
        """Test case for customers_customer_id_get

        get customer
        """
        pass

    async def test_customers_customer_id_post(self) -> None:
        """Test case for customers_customer_id_post

        create customer
        """
        pass

    async def test_customers_customer_id_put(self) -> None:
        """Test case for customers_customer_id_put

        update customer
        """
        pass


if __name__ == '__main__':
    unittest.main()
