# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.unit_response import UnitResponse

class TestUnitResponse(unittest.TestCase):
    """UnitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnitResponse:
        """Test UnitResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnitResponse`
        """
        model = UnitResponse()
        if include_optional:
            return UnitResponse(
                success = True,
                data = cool_open_client.client.models.unit_response_data.unitResponseData(
                    id = '', 
                    name = '', 
                    device = '', 
                    is_connected = True, 
                    supported_operation_statuses = [
                        56
                        ], 
                    supported_operation_modes = [
                        56
                        ], 
                    supported_fan_modes = [
                        56
                        ], 
                    supported_swing_modes = [
                        56
                        ], 
                    temperature_limits = cool_open_client.client.models.unit_response_data_temperature_limits.unitResponseData_temperatureLimits(
                        0 = [
                            56
                            ], 
                        1 = [
                            56
                            ], 
                        2 = [
                            56
                            ], ), 
                    brand = 56, 
                    active_setpoint = 56, 
                    ambient_temperature = 56, 
                    active_operation_status = 56, 
                    active_operation_mode = 56, 
                    active_fan_mode = 56, 
                    active_swing_mode = 56, 
                    filter = True, 
                    enable_cool_mode = True, 
                    enable_heat_mode = True, 
                    enable_auto_mode = True, 
                    is_half_c_degree_enabled = True, )
            )
        else:
            return UnitResponse(
        )
        """

    def testUnitResponse(self):
        """Test UnitResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
