# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.zone_control_switches_body import ZoneControlSwitchesBody

class TestZoneControlSwitchesBody(unittest.TestCase):
    """ZoneControlSwitchesBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZoneControlSwitchesBody:
        """Test ZoneControlSwitchesBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZoneControlSwitchesBody`
        """
        model = ZoneControlSwitchesBody()
        if include_optional:
            return ZoneControlSwitchesBody(
                mode = 56
            )
        else:
            return ZoneControlSwitchesBody(
                mode = 56,
        )
        """

    def testZoneControlSwitchesBody(self):
        """Test ZoneControlSwitchesBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
