# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.device_api import DeviceApi


class TestDeviceApi(unittest.IsolatedAsyncioTestCase):
    """DeviceApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DeviceApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_devices_device_id_delete(self) -> None:
        """Test case for devices_device_id_delete

        delete device
        """
        pass

    async def test_devices_device_id_get(self) -> None:
        """Test case for devices_device_id_get

        get device
        """
        pass

    async def test_devices_device_id_put(self) -> None:
        """Test case for devices_device_id_put

        update device
        """
        pass


if __name__ == '__main__':
    unittest.main()
