# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.customer_sites_api import CustomerSitesApi


class TestCustomerSitesApi(unittest.IsolatedAsyncioTestCase):
    """CustomerSitesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CustomerSitesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_customers_customer_id_sites_get(self) -> None:
        """Test case for customers_customer_id_sites_get

        get customer sites
        """
        pass

    async def test_customers_customer_id_sites_post(self) -> None:
        """Test case for customers_customer_id_sites_post

        create customer site
        """
        pass


if __name__ == '__main__':
    unittest.main()
