# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.api.systems_api import SystemsApi  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestSystemsApi(unittest.TestCase):
    """SystemsApi unit test stubs"""

    def setUp(self):
        self.api = SystemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_systems_get(self):
        """Test case for systems_get

        get my systems  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
