# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.websocket_api import WebsocketApi


class TestWebsocketApi(unittest.IsolatedAsyncioTestCase):
    """WebsocketApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = WebsocketApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_ws_v2_get(self) -> None:
        """Test case for ws_v2_get

        Websocket connection endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
