# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.types_response_data_hvac_brands_inner import TypesResponseDataHvacBrandsInner

class TestTypesResponseDataHvacBrandsInner(unittest.TestCase):
    """TypesResponseDataHvacBrandsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesResponseDataHvacBrandsInner:
        """Test TypesResponseDataHvacBrandsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesResponseDataHvacBrandsInner`
        """
        model = TypesResponseDataHvacBrandsInner()
        if include_optional:
            return TypesResponseDataHvacBrandsInner(
                value = 56,
                type = '',
                name = '',
                is_water_heater = True,
                has_booster = True
            )
        else:
            return TypesResponseDataHvacBrandsInner(
        )
        """

    def testTypesResponseDataHvacBrandsInner(self):
        """Test TypesResponseDataHvacBrandsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
