# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.models.create_system_request_body import CreateSystemRequestBody  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestCreateSystemRequestBody(unittest.TestCase):
    """CreateSystemRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateSystemRequestBody(self):
        """Test CreateSystemRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cool_open_client.client.models.create_system_request_body.CreateSystemRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
