# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.bad_response403 import BadResponse403

class TestBadResponse403(unittest.TestCase):
    """BadResponse403 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BadResponse403:
        """Test BadResponse403
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BadResponse403`
        """
        model = BadResponse403()
        if include_optional:
            return BadResponse403(
                success = True,
                message = ''
            )
        else:
            return BadResponse403(
        )
        """

    def testBadResponse403(self):
        """Test BadResponse403"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
