# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: none@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.api.unit_control_api import UnitControlApi  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestUnitControlApi(unittest.TestCase):
    """UnitControlApi unit test stubs"""

    def setUp(self):
        self.api = UnitControlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_units_unit_id_controls_fan_modes_put(self):
        """Test case for units_unit_id_controls_fan_modes_put

        set unit fan mode  # noqa: E501
        """
        pass

    def test_units_unit_id_controls_operation_modes_put(self):
        """Test case for units_unit_id_controls_operation_modes_put

        set unit operation mode  # noqa: E501
        """
        pass

    def test_units_unit_id_controls_operation_statuses_put(self):
        """Test case for units_unit_id_controls_operation_statuses_put

        set unit operation status  # noqa: E501
        """
        pass

    def test_units_unit_id_controls_setpoints_put(self):
        """Test case for units_unit_id_controls_setpoints_put

        set unit temperature setpoint  # noqa: E501
        """
        pass

    def test_units_unit_id_controls_swing_modes_put(self):
        """Test case for units_unit_id_controls_swing_modes_put

        set unit louver mode  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
