# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.customer_users_api import CustomerUsersApi


class TestCustomerUsersApi(unittest.IsolatedAsyncioTestCase):
    """CustomerUsersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CustomerUsersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_customers_customer_id_users_get(self) -> None:
        """Test case for customers_customer_id_users_get

        get customer users
        """
        pass

    async def test_customers_customer_id_users_post(self) -> None:
        """Test case for customers_customer_id_users_post

        create customer user
        """
        pass


if __name__ == '__main__':
    unittest.main()
