# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.sites_response import SitesResponse

class TestSitesResponse(unittest.TestCase):
    """SitesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SitesResponse:
        """Test SitesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SitesResponse`
        """
        model = SitesResponse()
        if include_optional:
            return SitesResponse(
                success = True,
                data = cool_open_client.client.models.sites_response_data.sitesResponse_data(
                    <site_id> = cool_open_client.client.models.site_response_data.siteResponseData(
                        id = '', 
                        name = '', 
                        description = '', 
                        country = '', 
                        city = '', 
                        postal_code = '', 
                        address = '', 
                        timezone = '', 
                        customer = '', 
                        devices = [
                            ''
                            ], 
                        zones = [
                            ''
                            ], 
                        systems = [
                            ''
                            ], 
                        role = cool_open_client.client.models.role.role(), ), )
            )
        else:
            return SitesResponse(
        )
        """

    def testSitesResponse(self):
        """Test SitesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
