# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.customers_api import CustomersApi


class TestCustomersApi(unittest.IsolatedAsyncioTestCase):
    """CustomersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CustomersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_customers_get(self) -> None:
        """Test case for customers_get

        get my customers
        """
        pass


if __name__ == '__main__':
    unittest.main()
