# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.unit_control_fans_body import UnitControlFansBody

class TestUnitControlFansBody(unittest.TestCase):
    """UnitControlFansBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnitControlFansBody:
        """Test UnitControlFansBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnitControlFansBody`
        """
        model = UnitControlFansBody()
        if include_optional:
            return UnitControlFansBody(
                fan_mode = 56
            )
        else:
            return UnitControlFansBody(
                fan_mode = 56,
        )
        """

    def testUnitControlFansBody(self):
        """Test UnitControlFansBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
