# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.user_response_data import UserResponseData

class TestUserResponseData(unittest.TestCase):
    """UserResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserResponseData:
        """Test UserResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserResponseData`
        """
        model = UserResponseData()
        if include_optional:
            return UserResponseData(
                id = '',
                username = '',
                email = '',
                phone = '',
                role = cool_open_client.client.models.role.role(),
                permissions = cool_open_client.client.models.permissions.permissions()
            )
        else:
            return UserResponseData(
        )
        """

    def testUserResponseData(self):
        """Test UserResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
