# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.update_site_request_body import UpdateSiteRequestBody

class TestUpdateSiteRequestBody(unittest.TestCase):
    """UpdateSiteRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSiteRequestBody:
        """Test UpdateSiteRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateSiteRequestBody`
        """
        model = UpdateSiteRequestBody()
        if include_optional:
            return UpdateSiteRequestBody(
                name = '',
                description = '',
                country = '',
                city = '',
                postal_code = '',
                address = '',
                timezone = ''
            )
        else:
            return UpdateSiteRequestBody(
        )
        """

    def testUpdateSiteRequestBody(self):
        """Test UpdateSiteRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
