# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.zone_response import ZoneResponse

class TestZoneResponse(unittest.TestCase):
    """ZoneResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZoneResponse:
        """Test ZoneResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZoneResponse`
        """
        model = ZoneResponse()
        if include_optional:
            return ZoneResponse(
                success = True,
                data = cool_open_client.client.models.zone_response_data.zoneResponseData(
                    id = '', 
                    name = '', 
                    role = cool_open_client.client.models.role.role(), 
                    site = '', 
                    units = [
                        ''
                        ], )
            )
        else:
            return ZoneResponse(
        )
        """

    def testZoneResponse(self):
        """Test ZoneResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
