# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.api.site_systems_api import SiteSystemsApi  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestSiteSystemsApi(unittest.TestCase):
    """SiteSystemsApi unit test stubs"""

    def setUp(self):
        self.api = SiteSystemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sites_site_id_systems_get(self):
        """Test case for sites_site_id_systems_get

        get site systems  # noqa: E501
        """
        pass

    def test_sites_site_id_systems_post(self):
        """Test case for sites_site_id_systems_post

        create site system  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
