# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: none@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.models.update_site_request_body import UpdateSiteRequestBody  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestUpdateSiteRequestBody(unittest.TestCase):
    """UpdateSiteRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSiteRequestBody(self):
        """Test UpdateSiteRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cool_open_client.client.models.update_site_request_body.UpdateSiteRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
