# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.system_units_api import SystemUnitsApi


class TestSystemUnitsApi(unittest.IsolatedAsyncioTestCase):
    """SystemUnitsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SystemUnitsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_systems_system_id_units_get(self) -> None:
        """Test case for systems_system_id_units_get

        get system units
        """
        pass

    async def test_systems_system_id_units_unit_id_delete(self) -> None:
        """Test case for systems_system_id_units_unit_id_delete

        remove unit from system
        """
        pass

    async def test_systems_system_id_units_unit_id_post(self) -> None:
        """Test case for systems_system_id_units_unit_id_post

        add unit to system
        """
        pass


if __name__ == '__main__':
    unittest.main()
