# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.site_users_api import SiteUsersApi


class TestSiteUsersApi(unittest.IsolatedAsyncioTestCase):
    """SiteUsersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SiteUsersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_sites_site_id_users_get(self) -> None:
        """Test case for sites_site_id_users_get

        get site users
        """
        pass

    async def test_sites_site_id_users_post(self) -> None:
        """Test case for sites_site_id_users_post

        create site user
        """
        pass


if __name__ == '__main__':
    unittest.main()
