# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: none@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.api.units_api import UnitsApi  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestUnitsApi(unittest.TestCase):
    """UnitsApi unit test stubs"""

    def setUp(self):
        self.api = UnitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_units_get(self):
        """Test case for units_get

        get my units  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
