# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.systems_api import SystemsApi


class TestSystemsApi(unittest.IsolatedAsyncioTestCase):
    """SystemsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SystemsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_systems_get(self) -> None:
        """Test case for systems_get

        get my systems
        """
        pass


if __name__ == '__main__':
    unittest.main()
