# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.sites_api import SitesApi


class TestSitesApi(unittest.IsolatedAsyncioTestCase):
    """SitesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SitesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_sites_get(self) -> None:
        """Test case for sites_get

        get my sites
        """
        pass


if __name__ == '__main__':
    unittest.main()
