# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.bad_response500 import BadResponse500

class TestBadResponse500(unittest.TestCase):
    """BadResponse500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BadResponse500:
        """Test BadResponse500
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BadResponse500`
        """
        model = BadResponse500()
        if include_optional:
            return BadResponse500(
                success = True,
                message = ''
            )
        else:
            return BadResponse500(
        )
        """

    def testBadResponse500(self):
        """Test BadResponse500"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
