# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.users_response import UsersResponse

class TestUsersResponse(unittest.TestCase):
    """UsersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersResponse:
        """Test UsersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersResponse`
        """
        model = UsersResponse()
        if include_optional:
            return UsersResponse(
                success = True,
                data = cool_open_client.client.models.users_response_data.usersResponse_data(
                    <user_id> = cool_open_client.client.models.user_response_data.userResponseData(
                        id = '', 
                        username = '', 
                        email = '', 
                        phone = '', 
                        role = cool_open_client.client.models.role.role(), 
                        permissions = cool_open_client.client.models.permissions.permissions(), ), )
            )
        else:
            return UsersResponse(
        )
        """

    def testUsersResponse(self):
        """Test UsersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
