# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.services_api import ServicesApi


class TestServicesApi(unittest.IsolatedAsyncioTestCase):
    """ServicesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ServicesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_services_types_get(self) -> None:
        """Test case for services_types_get

        get system types for enumerations used in protocol
        """
        pass


if __name__ == '__main__':
    unittest.main()
