# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.site_systems_api import SiteSystemsApi


class TestSiteSystemsApi(unittest.IsolatedAsyncioTestCase):
    """SiteSystemsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SiteSystemsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_sites_site_id_systems_get(self) -> None:
        """Test case for sites_site_id_systems_get

        get site systems
        """
        pass

    async def test_sites_site_id_systems_post(self) -> None:
        """Test case for sites_site_id_systems_post

        create site system
        """
        pass


if __name__ == '__main__':
    unittest.main()
