# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.api.system_api import SystemApi  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_systems_system_id_delete(self):
        """Test case for systems_system_id_delete

        delete system  # noqa: E501
        """
        pass

    def test_systems_system_id_get(self):
        """Test case for systems_system_id_get

        get system  # noqa: E501
        """
        pass

    def test_systems_system_id_put(self):
        """Test case for systems_system_id_put

        update system  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
