# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.user_api import UserApi


class TestUserApi(unittest.IsolatedAsyncioTestCase):
    """UserApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UserApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_users_user_id_delete(self) -> None:
        """Test case for users_user_id_delete

        delete user
        """
        pass

    async def test_users_user_id_get(self) -> None:
        """Test case for users_user_id_get

        get user
        """
        pass

    async def test_users_user_id_put(self) -> None:
        """Test case for users_user_id_put

        update user
        """
        pass


if __name__ == '__main__':
    unittest.main()
