# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.system_control_api import SystemControlApi


class TestSystemControlApi(unittest.IsolatedAsyncioTestCase):
    """SystemControlApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SystemControlApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_systems_system_id_controls_modes_put(self) -> None:
        """Test case for systems_system_id_controls_modes_put

        set system active operation mode for all units
        """
        pass

    async def test_systems_system_id_controls_switches_put(self) -> None:
        """Test case for systems_system_id_controls_switches_put

        set system active operation status for all units
        """
        pass


if __name__ == '__main__':
    unittest.main()
