# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.IsolatedAsyncioTestCase):
    """AuthenticationApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AuthenticationApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_users_authenticate_post(self) -> None:
        """Test case for users_authenticate_post

        authenticate
        """
        pass


if __name__ == '__main__':
    unittest.main()
