# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.api.device_api import DeviceApi  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_devices_device_id_delete(self):
        """Test case for devices_device_id_delete

        delete device  # noqa: E501
        """
        pass

    def test_devices_device_id_get(self):
        """Test case for devices_device_id_get

        get device  # noqa: E501
        """
        pass

    def test_devices_device_id_put(self):
        """Test case for devices_device_id_put

        update device  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
