# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.unit_api import UnitApi


class TestUnitApi(unittest.IsolatedAsyncioTestCase):
    """UnitApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UnitApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_units_unit_id_get(self) -> None:
        """Test case for units_unit_id_get

        get unit
        """
        pass

    async def test_units_unit_id_put(self) -> None:
        """Test case for units_unit_id_put

        update unit
        """
        pass


if __name__ == '__main__':
    unittest.main()
