# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: info@coolautomation.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cool_open_client.client
from cool_open_client.client.models.users_response import UsersResponse  # noqa: E501
from cool_open_client.client.rest import ApiException


class TestUsersResponse(unittest.TestCase):
    """UsersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsersResponse(self):
        """Test UsersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cool_open_client.client.models.users_response.UsersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
