# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.okresponse_with_id_data import OkresponseWithIdData

class TestOkresponseWithIdData(unittest.TestCase):
    """OkresponseWithIdData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OkresponseWithIdData:
        """Test OkresponseWithIdData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OkresponseWithIdData`
        """
        model = OkresponseWithIdData()
        if include_optional:
            return OkresponseWithIdData(
                id = ''
            )
        else:
            return OkresponseWithIdData(
        )
        """

    def testOkresponseWithIdData(self):
        """Test OkresponseWithIdData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
