# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.models.site_response_data import SiteResponseData

class TestSiteResponseData(unittest.TestCase):
    """SiteResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteResponseData:
        """Test SiteResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteResponseData`
        """
        model = SiteResponseData()
        if include_optional:
            return SiteResponseData(
                id = '',
                name = '',
                description = '',
                country = '',
                city = '',
                postal_code = '',
                address = '',
                timezone = '',
                customer = '',
                devices = [
                    ''
                    ],
                zones = [
                    ''
                    ],
                systems = [
                    ''
                    ],
                role = cool_open_client.client.models.role.role()
            )
        else:
            return SiteResponseData(
        )
        """

    def testSiteResponseData(self):
        """Test SiteResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
