# coding: utf-8

"""
    OpenClientCoolAutomationAPI

    Cool platform REST API

    The version of the OpenAPI document: 2.0.1
    Contact: none@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cool_open_client.client.api.unit_control_api import UnitControlApi


class TestUnitControlApi(unittest.IsolatedAsyncioTestCase):
    """UnitControlApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UnitControlApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_units_unit_id_controls_fan_modes_put(self) -> None:
        """Test case for units_unit_id_controls_fan_modes_put

        set unit fan mode
        """
        pass

    async def test_units_unit_id_controls_operation_modes_put(self) -> None:
        """Test case for units_unit_id_controls_operation_modes_put

        set unit operation mode
        """
        pass

    async def test_units_unit_id_controls_operation_statuses_put(self) -> None:
        """Test case for units_unit_id_controls_operation_statuses_put

        set unit operation status
        """
        pass

    async def test_units_unit_id_controls_setpoints_put(self) -> None:
        """Test case for units_unit_id_controls_setpoints_put

        set unit temperature setpoint
        """
        pass

    async def test_units_unit_id_controls_swing_modes_put(self) -> None:
        """Test case for units_unit_id_controls_swing_modes_put

        set unit louver mode
        """
        pass


if __name__ == '__main__':
    unittest.main()
